version: "3"
services:

  workspace:
    image: jupyter/pyspark-notebook:latest
    container_name: workspace
    user: root
    ports:
      - "8888:8888"
    networks:
      - production-network
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' "

  postgresql:
    image: postgres:12.17-alpine3.19
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - production-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - production-network
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - production-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  production-network:
    driver: bridge
  
